### ISSUE TITLE
We need create a action which works before every pull request[New Action]

### ISSUE THREAD

**Issue by rhmkstk** [LUI-UI/lui-vue#36]
**Is your feature request related to a problem? Please describe.**
We need to have an action to check all pull request are proper. Dependency install, package build, lint, type check ,storybook build.

**Describe the solution you'd like**
Create a yaml file in the .github folder to create a action

**Describe alternatives you've considered**

**Additional context**

**Comment by barathrum54** [comment]
I'll research this issue and find a proper solution for it.
