### ISSUE TITLE
Storybook template rendering issue

### ISSUE THREAD

**Issue by barathrum54** [LUI-UI/lui-vue#38]
### Describe the bug

Storybook template does not render the template properly on the show code panel. 
Expected behaviour is to see the SVG with the given components tags.
Which is not visible at the current stage.

### What version of do you have in package.json?

0.63.6

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rhmkstk** [comment]
We can fix this applying a code parameter to story
