### ISSUE TITLE
We need to organise branch/release management

### ISSUE THREAD

**Issue by rhmkstk** [LUI-UI/lui-vue#49]
**Is your feature request related to a problem? Please describe.**
We release the new version every main merge, and all issues merged with dev. We need the change this flow to better package management. Main branch: current version, dev branch: new version, a branch for every supported versions.

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by barathrum54** [comment]
- Figured out a better solution with a simpler workflow structure.

**Comment by barathrum54** [comment]
-

**Comment by barathrum54** [comment]
Figured out a better solution with a simpler workflow structure.
