### ISSUE TITLE
We need Alert component[New component]

### ISSUE THREAD

**Issue by ABB65** [LUI-UI/lui-vue#75]
**Is your feature request related to a problem? Please describe.**

We do not have a component that complies with LUI standards to display alerts that we can use on interactive web pages.

**Describe the solution you'd like**
With the example [here](https://www.w3.org/WAI/ARIA/apg/patterns/alert/examples/alert/), a component that is compatible with Lui colors and Style Guide should be prepared in accordance with accessibility standards.
Traditionally, Icon Slots' on/off option and content props should be specified.

**Comment by rhmkstk** [comment]
#163
